const API='https://api.binance.com/api/v3';
const TARGET_THRESHOLD=0.02;
const INTERVALS={'1m':{label:'1 minuto',ms:60000},'5m':{label:'5 minutos',ms:300000}};
let candles=[];let lastClosedTime=null;
const $=id=>document.getElementById(id);
const num=n=>{const v=Number(n);return Number.isFinite(v)?v:null};
const fmt=n=>{const v=num(n);return v===null?'—':v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:8})};
const symbol=()=>$("symbol").value;const interval=()=>$("interval")?.value||'1m';const intervalInfo=()=>INTERVALS[interval()]||INTERVALS['1m'];
const key=()=>`cp-predictions-${symbol()}-${interval()}`;
function getHistory(){try{const a=JSON.parse(localStorage.getItem(key())||'[]');return Array.isArray(a)?a.map(normalizePrediction).filter(Boolean):[]}catch{return[]}}
function saveHistory(a){localStorage.setItem(key(),JSON.stringify(a.slice(-500)))}
function normalizePrediction(p){if(!p||!Number.isFinite(Number(p.time)))return null;const entry=num(p.entry??p.price);let tp=num(p.tp),sl=num(p.sl);const signal=p.signal;if(entry!==null&&signal&&signal!=='NEUTRAL'&&(tp===null||sl===null)){const risk=entry*0.002;tp=signal==='BAJADA'?entry-risk:entry+risk;sl=signal==='BAJADA'?entry+risk:entry-risk}return {...p,time:Number(p.time),entry,tp,sl,price:entry??num(p.price)}}
function ema(a,n){if(!a.length)return 0;const k=2/(n+1);let v=a[0].c;for(let i=1;i<a.length;i++)v=a[i].c*k+v*(1-k);return v}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i].c-a[i-1].c;if(d>0)g+=d;else l-=d}return l?100-100/(1+g/l):100}
function volatility(a,n=20){if(a.length<n+1)return 0;const rs=[];for(let i=a.length-n;i<a.length;i++)rs.push(Math.log(a[i].c/a[i-1].c));const m=rs.reduce((x,v)=>x+v,0)/rs.length;return Math.sqrt(rs.reduce((x,v)=>x+(v-m)**2,0)/rs.length)*100}
function direction(from,to){const pct=(to.c/from.c-1)*100;if(pct>TARGET_THRESHOLD)return 'SUBIDA';if(pct<-TARGET_THRESHOLD)return 'BAJADA';return 'NEUTRAL'}
function resolveTrade(p,newCandle){if(!p||p.tradeResult||p.result||p.signal==='NEUTRAL')return p;p=normalizePrediction(p);if(!p||p.entry===null||p.tp===null||p.sl===null)return p;let hitTp=false,hitSl=false;if(p.signal==='SUBIDA'){hitTp=newCandle.h>=p.tp;hitSl=newCandle.l<=p.sl}else if(p.signal==='BAJADA'){hitTp=newCandle.l<=p.tp;hitSl=newCandle.h>=p.sl}const closeResult=hitTp&&hitSl?'INDETERMINADO':hitTp?'TAKE_PROFIT':hitSl?'STOP_LOSS':'SIN_SALIDA';p.result=direction({c:p.entry},newCandle);p.movePct=(newCandle.c/p.entry-1)*100;p.highPct=(newCandle.h/p.entry-1)*100;p.lowPct=(newCandle.l/p.entry-1)*100;p.tradeResult=closeResult;p.correct=closeResult==='TAKE_PROFIT';p.evaluatedAt=Date.now();p.exitPrice=newCandle.c;p.exitTime=newCandle.t;p.exitReason=hitTp&&hitSl?'TP y SL tocados en la misma vela':hitTp?'TAKE PROFIT':hitSl?'STOP LOSS':'CIERRE DE VELA';return p}
function evaluatePending(newClosed){if(!newClosed)return;const h=getHistory();let changed=false;for(const p of h){if(!p.result&&p.signal!=='NEUTRAL'&&p.time<newClosed.t){resolveTrade(p,newClosed);changed=true}}if(changed)saveHistory(h);renderStats();renderHistory();renderActiveTrade()}
function registerPrediction(closed,signal,strength,tp,sl){const h=getHistory();if(h.some(x=>x.time===closed.t))return;h.push({id:`${symbol()}-${interval()}-${closed.t}`,symbol:symbol(),interval:interval(),time:closed.t,price:closed.c,entry:closed.c,signal,strength,tp:signal==='NEUTRAL'?null:tp,sl:signal==='NEUTRAL'?null:sl});saveHistory(h);renderStats();renderHistory();renderActiveTrade()}
function renderStats(){const a=getHistory().filter(x=>x.tradeResult);const wins=a.filter(x=>x.correct).length;const acc=a.length?wins/a.length*100:0;const el=$('stats');if(el)el.textContent=`Pruebas: ${a.length} · Aciertos: ${wins} · Precisión: ${acc.toFixed(1)}%`;const bar=$('accuracyBar');if(bar)bar.style.width=`${Math.min(100,acc)}%`}
function tradeBadge(x){if(x.tradeResult==='TAKE_PROFIT')return '🎯 TAKE PROFIT';if(x.tradeResult==='STOP_LOSS')return '🛑 STOP LOSS';if(x.tradeResult==='INDETERMINADO')return '⚠️ TP + SL';return x.result||'—'}
function renderHistory(){const body=$('history');if(!body)return;body.innerHTML=getHistory().filter(x=>x.tradeResult).slice(-15).reverse().map(x=>`<tr><td>${new Date(x.time).toLocaleTimeString()}</td><td>${x.signal}</td><td>${num(x.strength)?.toFixed(0)??'—'}%</td><td>${fmt(x.entry)}</td><td>${fmt(x.tp)}</td><td>${fmt(x.sl)}</td><td>${tradeBadge(x)}<br><small>${num(x.movePct)!==null?(x.movePct>=0?'+':'')+x.movePct.toFixed(3)+'%':''} · salida ${fmt(x.exitPrice)}</small></td></tr>`).join('')||'<tr><td colspan="7">Todavía no hay operaciones simuladas cerradas.</td></tr>'}
function renderActiveTrade(){const el=$('activeTrade');if(!el)return;const h=getHistory(),p=h.filter(x=>!x.tradeResult&&x.signal!=='NEUTRAL'&&x.entry!==null).sort((a,b)=>b.time-a.time)[0];if(!p){el.innerHTML='<span class="muted">No hay movimiento activo. La última señal puede ser NEUTRAL o ya fue evaluada.</span>';return}el.innerHTML=`<div class="active-head"><b>🟢 MOVIMIENTO ACTIVO · ${p.signal}</b><span>${num(p.strength)?.toFixed(0)??'—'}% fuerza</span></div><div class="active-grid"><div>Entrada <b>${fmt(p.entry)}</b></div><div>Take Profit <b>${fmt(p.tp)}</b></div><div>Stop Loss <b>${fmt(p.sl)}</b></div><div>Intervalo <b>${intervalInfo().label}</b></div></div><small>Abierto ${new Date(p.time).toLocaleTimeString()} · esperando cierre de la siguiente vela para confirmar TP, SL o cierre.</small>`}
function ensureTradeUi(){if($('activeTrade'))return;const historyTable=$('history');if(historyTable){const wrap=historyTable.closest('.panel');if(wrap){const active=document.createElement('section');active.className='panel';active.innerHTML='<div class="title"><h2>Movimiento activo</h2><small>Seguimiento en tiempo real</small></div><div id="activeTrade"><span>No hay movimiento activo.</span></div>';wrap.parentNode.insertBefore(active,wrap);const table=historyTable.closest('table');if(table){const head=table.querySelector('thead tr');if(head)head.innerHTML='<th>Hora</th><th>Señal</th><th>Fuerza</th><th>Entrada</th><th>Take Profit</th><th>Stop Loss</th><th>Resultado</th>';}}}}
function draw(){const c=$('chart'),ctx=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth*d,h=c.clientHeight*d;c.width=w;c.height=h;ctx.clearRect(0,0,w,h);const a=candles.slice(-60);if(!a.length)return;const left=8*d,right=78*d,top=18*d,bottom=22*d,plotW=Math.max(1,w-left-right),plotH=Math.max(1,h-top-bottom);const min=Math.min(...a.map(x=>x.l)),max=Math.max(...a.map(x=>x.h)),range=max-min||1,y=v=>top+(max-v)/range*plotH,cw=Math.max(2*d,plotW/a.length*.62);ctx.font=`${12*d}px sans-serif`;ctx.textAlign='right';ctx.textBaseline='middle';ctx.lineWidth=Math.max(1,d);for(let i=0;i<=5;i++){const price=max-range*(i/5),yy=y(price);ctx.strokeStyle='rgba(148,163,184,.16)';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(left+plotW,yy);ctx.stroke();ctx.fillStyle='rgba(203,213,225,.82)';ctx.fillText(fmt(price),w-6*d,yy)}a.forEach((x,i)=>{const xx=left+(i+.5)*plotW/a.length;ctx.strokeStyle=x.c>=x.o?'#39d98a':'#ff6b6b';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(x.h));ctx.lineTo(xx,y(x.l));ctx.stroke();const topBody=y(Math.max(x.o,x.c)),botBody=y(Math.min(x.o,x.c));ctx.fillRect(xx-cw/2,topBody,cw,Math.max(2*d,botBody-topBody))});const live=a.at(-1)?.c;const closed=a.at(-2)?.c;const last=live??closed;if(num(last)!==null){const yy=Math.max(top,Math.min(top+plotH,y(last)));ctx.setLineDash([4*d,4*d]);ctx.strokeStyle='rgba(250,250,250,.55)';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(left+plotW,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#172033';ctx.fillRect(w-right+3*d,yy-10*d,right-9*d,20*d);ctx.fillStyle='#fff';ctx.font=`bold ${12*d}px sans-serif`;ctx.textAlign='center';ctx.fillText(fmt(last),w-right/2+2*d,yy)}ctx.fillStyle='rgba(148,163,184,.8)';ctx.font=`${10*d}px sans-serif`;ctx.textAlign='left';ctx.fillText('Precio',left,10*d)}
function predict(closed){const usable=candles.slice(0,-1),e9=ema(usable,9),e21=ema(usable,21),rs=rsi(usable),vol=volatility(usable),last=closed,prev=usable.at(-2);if(!prev)return;const mom=(last.c-prev.c)/prev.c*100,avgVol=usable.slice(-20).reduce((s,x)=>s+x.v,0)/Math.min(20,usable.length),volRatio=avgVol?last.v/avgVol:1;let score=0;const reasons=[];if(last.c>e9){score+=.8;reasons.push('Precio > EMA9')}else{score-=.8;reasons.push('Precio < EMA9')}if(e9>e21){score+=1;reasons.push('EMA9 > EMA21')}else{score-=1;reasons.push('EMA9 < EMA21')}if(mom>0){score+=.8;reasons.push(`Momentum +${mom.toFixed(3)}%`)}else{score-=.8;reasons.push(`Momentum ${mom.toFixed(3)}%`)}if(rs>55){score+=.5;reasons.push(`RSI fuerte (${rs.toFixed(1)})`)}else if(rs<45){score-=.5;reasons.push(`RSI débil (${rs.toFixed(1)})`)}else reasons.push(`RSI neutral (${rs.toFixed(1)})`);if(volRatio>1.2){score+=mom>0?.3:-.3;reasons.push(`Volumen ${volRatio.toFixed(2)}x promedio`)}else reasons.push(`Volumen ${volRatio.toFixed(2)}x promedio`);let signal='NEUTRAL';if(score>=1.4)signal='SUBIDA';else if(score<=-1.4)signal='BAJADA';const strength=Math.min(94,50+Math.abs(score)*10);$('signal').textContent=signal;$('confidence').textContent=`Fuerza experimental: ${strength.toFixed(0)}% · RSI ${rs.toFixed(1)}`;$('rsi').textContent=rs.toFixed(1);$('ema9').textContent=fmt(e9);$('ema21').textContent=fmt(e21);$('volatility').textContent=`${vol.toFixed(3)}%`;$('signalReason').textContent=`${reasons.join(' · ')}. Puntaje ${score.toFixed(2)} → ${signal}.`;$('entry').textContent=fmt(last.c);let tp=null,sl=null;if(signal==='NEUTRAL'){$('tp').textContent='—';$('sl').textContent='—';$('riskNote').textContent='Sin niveles: señal neutral.'}else{const risk=Math.max(last.c*.0015,last.c*vol/100*1.5);tp=signal==='BAJADA'?last.c-risk:last.c+risk;sl=signal==='BAJADA'?last.c+risk:last.c-risk;$('tp').textContent=fmt(tp);$('sl').textContent=fmt(sl);$('riskNote').textContent='Operación simulada; no envía órdenes reales.'}registerPrediction(closed,signal,strength,tp,sl)}
function ensureIntervalControl(){if($('interval'))return;const toolbar=document.querySelector('.toolbar');if(!toolbar)return;const label=document.createElement('label');label.innerHTML=`Intervalo<select id="interval"><option value="1m">1 minuto</option><option value="5m">5 minutos</option></select>`;toolbar.insertBefore(label,toolbar.children[1]||null);$('interval').addEventListener('change',()=>{lastClosedTime=null;renderStats();renderHistory();renderActiveTrade();load()})}
async function load(){try{ensureTradeUi();ensureIntervalControl();$('status').textContent='Conectando…';const r=await fetch(`${API}/klines?symbol=${symbol()}&interval=${interval()}&limit=100`,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();candles=d.map(x=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}));const closed=candles.at(-2),current=candles.at(-1);evaluatePending(closed);lastClosedTime=closed.t;$('status').textContent='Conectado';$('price').textContent=fmt(current.c);const pct=(current.c/closed.c-1)*100;$('change').textContent=`${pct>=0?'+':''}${pct.toFixed(3)}% vela actual`;$('candle').textContent=closed.c>=closed.o?'Alcista':'Bajista';$('volume').textContent=`Volumen cerrado: ${closed.v.toFixed(2)}`;$('updated').textContent=new Date().toLocaleTimeString();$('dataInfo').textContent=`Binance · ${symbol()} · 100 velas de ${interval()} · última cerrada ${new Date(closed.t).toLocaleTimeString()} · precio actual de la vela en formación`;$('signal').closest('article').querySelector('span').textContent=`Próximo ${intervalInfo().label}`;document.querySelector('.panel .title h2').textContent=`Velas ${interval()}`;predict(closed);draw();renderActiveTrade()}catch(e){$('status').textContent='Error de conexión';$('dataInfo').textContent='No se pudieron obtener datos públicos de Binance en este momento.'}}
$('symbol').addEventListener('change',()=>{lastClosedTime=null;renderStats();renderHistory();renderActiveTrade();load()});$('refresh').addEventListener('click',load);$('clearStats').addEventListener('click',()=>{if(confirm('¿Borrar las estadísticas de '+symbol()+' en '+intervalInfo().label+'?')){localStorage.removeItem(key());renderStats();renderHistory();renderActiveTrade()}});ensureTradeUi();ensureIntervalControl();load();setInterval(load,10000);addEventListener('resize',draw);renderStats();renderHistory();renderActiveTrade();